include: [".well-known"]
exclude: ["readme.md", "Rakefile", "changelog.md"]
highlighter: rouge
markdown: rdiscount

rdiscount:
  extensions: [smart]

title: julioes.com

author:
  name: Julio Espinoza-Sokal
  email: julioes@gmail.com
  github: julioes
  twitter: jespinozasokal

production_url: https://www.julioes.com

permalink: /blog/:year/:month/:title

sass:
  style: compressed
